config/routes.rb
Rails.application.routes.draw do  
  get 'signals/index'

  

  devise_for :users
  resources :tag_types
  resources :devices
  resources :tags
  

  root 'dashboard#index'

  namespace :api do  
    namespace :v1 do
        resources :tag_values, :tags, :commands, :defaults => { :format => 'json' }
    end    
  end  

  get 'telecontrol', to: 'telecontrols#index'
  post 'telecontrol', to: 'telecontrols#create'
  get 'perfil', to: 'clients#edit'
  post 'perfil', to: 'clients#update'
  get 'configuration', to: 'configuration#index'
  put 'tag_alerts/:id' => 'tag_alerts#update'
  get 'tag_alerts' => 'tag_alerts#show'
  get 'tag_notices' => 'tag_alerts#show_notices'
  put 'tag_notices/:id' => 'tag_alerts#update_notices'
  get 'signals/detail/:id', to: 'signals#detail'
  

end

app/models/device.rb
class Device < ActiveRecord::Base
  belongs_to :model
  belongs_to :client  
  has_many :tags


  def full_name
    "#{model.name} - #{serial} - ip: #{ip}"
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.joins(:client, :model)
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.joins(:client, :model).find(params[:id])
  end

  # GET /devices/new
  def new
    @device = Device.new
    @model = Model.all
    #@client = Client.find(current_user.client_id)          
    @client = Client.where(id: current_user.client_id)

  end

  # GET /devices/1/edit
  def edit
    @model = Model.all
    @client = Client.where(id: current_user.client_id)
    #@client = Client.find(current_user.client_id) 
    #byebug             
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Dispositivo grabado correctamente.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'El Dispositivo fue actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'El Dispositivo fue Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:place, :serial, :ip,  :model_id, :client_id)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for @device, :html => {:id => "msg_validate", :novalidate =>  "novalidate"} do |f| %> 
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> Debe llenar los Siguientes Campos::</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="clearfix"></div>
<%= render 'shared/flash_messages' if !flash.empty? %>
<div class="clearfix"></div>

  <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
  <section class="box ">
      <header class="panel_header">
          <h2 class="title pull-left">Dispositivo</h2>
          <div class="actions panel_actions pull-right">                         
              
          </div>
      </header>
      <div class="content-body">
      <p>
      <div class="row">
              <div class="col-md-7 col-sm-7 col-xs-12">                   
                  <label for="inputEmail" class="col-sm-2 control-label">Place</label>                    
                  <div class="input-group">               
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-tag"></i>     
                      </span>                 
                      <%= f.text_field :place, class: 'form-control', placeholder: 'Ubicación del equipo' %>
                        
                  </div> 

                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Serial</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-location-arrow"></i>     
                      </span>                 
                      <%= f.text_field :serial, class: 'form-control', placeholder: 'Serial del equipo' %>
                  </div> 
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">IP</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-code-fork"></i>     
                      </span>
                      <%= f.text_field :ip, class: 'form-control', placeholder: 'IP asignada al equipo' %>
                  </div>                                            
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Modelo</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-toggle-down"></i>     
                      </span>
                      <%= f.select :model_id, @model.map{ |r| [r.name, r.id] }, {:prompt  => 'Seleccione modelo del equipo'}, {:class => 'form-control m-bot15'}  %>
                  </div>                    
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Cliente</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-toggle-down"></i>     
                      </span>
                      <%= f.select :client_id, @client.map{ |r| [r.name, r.id] },  {:prompt  => 'Seleccioe el cliente asociado'}, {:class => 'form-control m-bot15'} %>
                  </div>                   
                   <br> 
                <div class="col-md-12">                 
                    <%= f.submit 'Guardar', class: 'btn btn-success btn-icon bottom15 right15' %>                                       
                                                  
                    <%= link_to 'Regresar', devices_path , class:'btn btn-purple btn-icon bottom15 right15' %>
                </div> 

              </div> 
          </div>
        </div>
      </div>
  </section>
 </div>
<% end %>

app/views/devices/edit.html.erb
<%= render 'form' %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-12">
    <section class="box ">
        <header class="panel_header">
            <h2 class="title pull-left">Dispositivos</h2>
            <div class="actions panel_actions pull-right">
                <%= link_to 'Crear nuevo registro', new_device_path, class: 'btn btn-primary btn-xs' %>
                <!--i class="box_toggle fa fa-chevron-down"></i>
                <i class="box_setting fa fa-cog" data-toggle="modal" href="#section-settings"></i>
                <i class="box_close fa fa-times"></i-->
            </div>
        </header>
        <div class="content-body">    
            <div class="row">
            <% @devices.each do |device| %>
                <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
                    <div class="tile-counter bg-primary">
                        <div class="content">
                            <i class='fa fa-laptop icon-lg'></i>
                            <h2 class="number_counter1" data-speed="3000" data-from="1001" data-to="3504">ID: <%= device.id %></h2>
                            <span><%= device.place %></span>
                            <span>S/N <%= device.serial %></span>
                            <br>
                            <div class="btn-group btn-group-justified">
                            <%= link_to 'Editar', edit_device_path(device), class: 'btn btn-blue btn-xs', type:'button' %>
                            <%= link_to 'Eliminar', device, method: :delete, data: { confirm: 'Estas Seguro de Borrar este Dispositivo?' }, class: 'btn btn-danger btn-xs', type:'button' %>      
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
                <div class="clearfix"></div>
            </div>
        </div>
    </section>
</div>

app/views/devices/new.html.erb
<%= render 'form' %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 sort_panel">
  <section class="box purple">
    <header class="panel_header">
        <h2 class="title pull-left">Dispositivo</h2>
        <div class="actions panel_actions pull-right">
            <i class="box_toggle fa fa-chevron-down"></i>
            <i class="box_setting fa fa-cog" data-toggle="modal" href="#section-settings"></i>
            <i class="box_close fa fa-times"></i>
        </div>
    </header>
    <div class="content-body">    
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <p>
              <strong>Place:</strong>
              <%= @device.place %>
            </p>

            <p>
              <strong>Serial:</strong>
              <%= @device.serial %>
            </p>

            <p>
              <strong>Ip:</strong>
              <%= @device.ip %>
            </p>

            <p>
              <strong>Modelo:</strong>
              <%= @device.model.name %>
            </p>

            <p>
              <strong>Cliente:</strong>
              <%= @device.client.name %>
            </p>

        </div>
        <div class="col-md-12">                 
           <%= link_to 'Editar', edit_device_path(@device) , class:'btn btn-success btn-icon bottom15 right15' %>  
           <%= link_to 'Regresar', devices_path , class:'btn btn-primary btn-icon bottom15 right15' %>
        </div> 
      </div>
    </div>
  </section>
</div>