config/routes.rb
Rails.application.routes.draw do  
  get 'signals/index'

  

  devise_for :users
  resources :tag_types
  resources :devices
  resources :tags
  

  root 'dashboard#index'

  namespace :api do  
    namespace :v1 do
        resources :tag_values, :tags, :commands, :defaults => { :format => 'json' }
    end    
  end  

  get 'telecontrol', to: 'telecontrols#index'
  post 'telecontrol', to: 'telecontrols#create'
  get 'perfil', to: 'clients#edit'
  post 'perfil', to: 'clients#update'
  get 'configuration', to: 'configuration#index'
  put 'tag_alerts/:id' => 'tag_alerts#update'
  get 'tag_alerts' => 'tag_alerts#show'
  get 'tag_notices' => 'tag_alerts#show_notices'
  put 'tag_notices/:id' => 'tag_alerts#update_notices'
  get 'signals/detail/:id', to: 'signals#detail'
  

end

app/views/shared/template_layout_application/_box_modal.html.erb
<div class="modal" id="section-settings" tabindex="-1" role="dialog" aria-labelledby="ultraModal-Label" aria-hidden="true">
    <div class="modal-dialog animated bounceInDown">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Section Settings</h4>
            </div>
            <div class="modal-body">

                Body goes here...

            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
                <button class="btn btn-success" type="button">Save changes</button>
            </div>
        </div>
    </div>
</div>

app/views/shared/template_layout_application/_breadcrumbs.html.erb
<div class='col-lg-12 col-md-12 col-sm-12 col-xs-12'>
    <div class="page-title">
        <div class="pull-left">
            <h1 class="title">Tablero</h1>                            
        </div>
        <div class="pull-right hidden-xs">
            <ol class="breadcrumb">
                <li>
                    <a href="index.html"><i class="fa fa-home"></i>Tablero</a>
                </li>
                <li>
                    <a href="layout-default.html">Layouts</a>
                </li>
                <li class="active">
                    <strong>Principal</strong>
                </li>
            </ol>
        </div>
    </div>
</div>

app/views/shared/template_layout_application/_list_main_menu.html.erb
<ul class='wraplist'> 
    <li class="">
        <%= link_to '<i class="fa fa-dashboard"></i><span class="title">Tablero</span>'.html_safe, root_path %> 
    </li>

    <li class="">
        <%= link_to '<i class="fa fa-signal"></i><span class="title">Señales</span>'.html_safe, signals_index_path %> 
    </li>
    
    <li class="">
        <%= link_to '<i class="fa fa-gears"></i><span class="title">Telecontroles</span>'.html_safe, telecontrol_path %>
    </li>

    <li class="">
        <%= link_to '<i class="fa fa-sliders"></i><span class="title">Configuración</span>'.html_safe, configuration_path %> 
    </li>
</ul>

app/views/shared/template_layout_application/_top_bar.html.erb
<div class='page-topbar'>
    <div class='logo-area'>

    </div>
    <div class='quick-area'>
        <div class='pull-left'>
            <ul class="info-menu left-links list-inline list-unstyled">
                <li class="sidebar-toggle-wrap">
                    <a href="#" data-toggle="sidebar" class="sidebar_toggle">
                        <i class="fa fa-bars"></i>
                    </a>
                </li>
            </ul>
        </div>    
        <div class='pull-right'>
            <ul class="info-menu right-links list-inline list-unstyled">
                <li class="profile">
                    <a href="#" data-toggle="dropdown" class="toggle">
                        <img src="<%= image_path 'data/profile/logo.png' %>"alt="user-image" class="img-circle img-inline">
                        <span> <%= current_user.full_name %> <i class="fa fa-angle-down"></i></span>
                    </a>
                    <ul class="dropdown-menu profile animated fadeIn">
                        <li>
                            <a href="/configuration">
                                <i class="fa fa-wrench"></i>
                                Configuración
                            </a>
                        </li>
                        <li>
                            <a href="/perfil">
                                <i class="fa fa-user"></i>
                                Perfil
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-info"></i>
                                Ayuda
                            </a>
                        </li>
                        <li class="last">
                            <%= link_to(destroy_user_session_path, :method => :delete) do %>
                              <i class="fa fa-lock"></i>
                              Salir
                            <% end %>
                        </li>
                    </ul>
                </li> 
                <li class="chat-toggle-wrapper">
                    <a href="#" data-toggle="chatbar" class="toggle_chat">
                        <i class="fa fa-bell"></i>
                            <%= render :partial => 'tag_alerts/count_alerts' %>                        
                    </a>
                </li> 
                 <li class="chat-toggle-wrapper">
                    <a href="#" data-toggle="chatbar" class="toggle_chat">
                        <i class="fa fa-info-circle"></i>
                            <%= render :partial => 'tag_alerts/count_notices' %>                        
                    </a>
                </li>                                     
            </ul>     
        </div>    
    </div>

</div>

app/views/shared/template_layout_application/_user_info.html.erb
<div class="profile-info row">
    <div class="profile-image col-md-4 col-sm-4 col-xs-4">
        <a href="#">
            <img src="<%= image_path 'data/profile/logo.png' %>" class="img-responsive img-circle">
        </a>
    </div>              
    <div class="profile-details col-md-8 col-sm-8 col-xs-8">
        <h3>
            <a href="ui-profile.html"><%= current_user.full_name %></a>
        </h3>
    </div>
</div>