config/routes.rb
Rails.application.routes.draw do  
  get 'signals/index'

  

  devise_for :users
  resources :tag_types
  resources :devices
  resources :tags
  

  root 'dashboard#index'

  namespace :api do  
    namespace :v1 do
        resources :tag_values, :tags, :commands, :defaults => { :format => 'json' }
    end    
  end  

  get 'telecontrol', to: 'telecontrols#index'
  post 'telecontrol', to: 'telecontrols#create'
  get 'perfil', to: 'clients#edit'
  post 'perfil', to: 'clients#update'
  get 'configuration', to: 'configuration#index'
  put 'tag_alerts/:id' => 'tag_alerts#update'
  get 'tag_alerts' => 'tag_alerts#show'
  get 'tag_notices' => 'tag_alerts#show_notices'
  put 'tag_notices/:id' => 'tag_alerts#update_notices'
  get 'signals/detail/:id', to: 'signals#detail'
  

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  last_value = nil
  tag_alert = nil
  belongs_to :tag_type
  belongs_to :device
  has_one :client, through: :device
  has_many :tag_values

  validates :name,
  length: { maximum: 255 },
  presence: true
  validates :tag_type,
  presence: true
  validates :location,
  length: { maximum: 255 },
  presence: true
  validates :port,
  length: { maximum: 10 },
  presence: true
  validates :config,
  length: { maximum: 100 },
  presence: true
   validates :device_id,
  length: { maximum: 10 },
  presence: true

  scope :for_client, ->(client_id){ joins(:device).where("devices.client_id = ?",client_id)}
  scope :just_actuators, ->(){ joins(:tag_type).where("tag_types.tag_type = ?",TagType::ACTUATOR)}

  def last_value
    last_value ||= tag_values.last
  end
  def tag_alert
    tag_alert ||= TagAlert.for_tag_value(tag_values.last)
  end

  def as_json(options={})
    respond = super.as_json(options).merge({
        tag_type: tag_type,
        device: device,
        last_value: tag_values.last,
        tag_values: tag_values,
        tag_value_now: tag_values.today,
        tag_value_week: tag_values.week,
        tag_value_month: tag_values.last_month,
        tag_alert: TagAlert.for_tag_value(tag_values.last)
    })
  end

end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
  belongs_to :tags

  RANK = "rank"
  ACTUATOR = "actuator"

  def is_rank?
    tag_type == RANK
  end

  def is_actuator?
    tag_type == ACTUATOR
  end

end

app/controllers/api/v1/tags_controller.rb
class Api::V1::TagsController < Api::V1::BaseController
    
    respond_to :json

    # GET /api/{plural_resource_name}
    def index  
      plural_resource_name = "@#{resource_name.pluralize}"
      if params['client_id'] && params['device_id']
        resources = resource_class.joins(:device, :tag_type).where('devices.client_id = ? and device_id = ?', params['client_id'].to_i, params['device_id'].to_i)
                                  .page(page_params[:page])
                                  .per(page_params[:page_size])        
      else
        resources = resource_class.where(query_params)
                                  .page(page_params[:page])
                                  .per(page_params[:page_size])                
      end
      instance_variable_set(plural_resource_name, resources)
      respond_with instance_variable_get(plural_resource_name)
    end

    private

      def tag_value_params
        params.require(:tag).permit(:name, :tag_type_id, :location, :port, :config)
      end

      def query_params
        params.permit(:client_id, :name, :id, :device_id)
      end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.joins(:tag_type, :device)

    
  end

  # GET /tags/1
  # GET /tags/1.json
  def show    
    #@tag = Tag.joins(:tag_type, :device).where(id: params[:id])
    @tag = Tag.joins(:tag_type, :device).find(params[:id])
    #byebug
  end

  # GET /tags/new
  def new
    @tag = Tag.new
    @tag_type = TagType.all
    @device = Device.where(client_id: current_user.client_id)
    #byebug

  end

  # GET /tags/1/edit
  def edit
    @tag_type = TagType.all
    @device = Device.where(client_id: current_user.client_id)
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Sensor grabado correctamente.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'El Sensor se actualizo correctamente.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'El Sensor fue Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :tag_type_id, :location, :port, :config, :device_id, :normal_value, :warning_value, :danger_value, :humbral)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for @tag, :html => {:id => "msg_validate", :novalidate =>  "novalidate"} do |f| %> 
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> Debe llenar los Siguientes Campos::</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="clearfix"></div>
<%= render 'shared/flash_messages' if !flash.empty? %>
<div class="clearfix"></div>

  <div class="col-lg-12 col-md-12 col-xs-12 col-sm-12">
  <section class="box ">
      <header class="panel_header">
          <h2 class="title pull-left">Sensor</h2>
          <div class="actions panel_actions pull-right">                         
              
          </div>
      </header>
      <div class="content-body">
      <p>
      <div class="row">
              <div class="col-md-8 col-sm-8 col-xs-12">                   
                  <label for="inputEmail" class="col-sm-2 control-label">Nombre</label>                                      
                  <div class="input-group">               
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-tag"></i>     
                      </span>                 
                      <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre del Sensor' %>
                  </div> 

                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Locación</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-location-arrow"></i>     
                      </span>                 
                      <%= f.text_field :location, class: 'form-control', placeholder: '' %>
                  </div> 
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Puerto</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-code-fork"></i>     
                      </span>
                      <%= f.text_field :port, class: 'form-control', placeholder: 'Puerto' %>
                  </div>                   
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Config.</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-cogs"></i>     
                      </span>
                      <%= f.text_field :config, class: 'form-control', placeholder: 'Configuracion del equipo' %>
                  </div>
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Alerta VN</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-arrows-v"></i>     
                      </span>
                      <%= f.text_field :normal_value, class: 'form-control', placeholder: 'Valor del alerta con un estado Normal' %>
                  </div>
                                    <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Alerta VA</label>                                    
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-warning"></i>     
                      </span>
                      <%= f.text_field :warning_value, class: 'form-control', placeholder: 'Valor del alerta con un estado en Advertencia' %>
                  </div>
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Alerta VP</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-recycle"></i>     
                      </span>
                      <%= f.text_field :danger_value, class: 'form-control', placeholder: 'Valor del alerta con un estado de Peligro' %>
                      <%= f.hidden_field :humbral, :value => 10 %>
                  </div>               
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Tipo</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-toggle-down"></i>     
                      </span>
                      <%= f.select :tag_type_id, @tag_type.map{ |r| [r.name, r.id] }, {:prompt  => 'Seleccione el tipo de sensor...'}, {:class => 'form-control m-bot15'}  %>
                  </div>                 
                  <br>
                  <label for="inputEmail" class="col-sm-2 control-label">Dispositivo</label>
                  <div class="input-group">
                      <span class="input-group-addon">
                          <span class="arrow"></span>
                          <i class="fa fa-toggle-down"></i>     
                      </span>
                      <%= f.select :device_id, @device.map{ |r| [r.ip, r.id] },  {:prompt  => 'Seleccione el dispositivo...'}, {:class => 'form-control m-bot15'} %>
                  </div>                  
                 <br> 
                <div class="col-md-12">                 
                    <%= f.submit 'Guardar', class: 'btn btn-success btn-icon bottom15 right15' %>                                       
                                                  
                    <%= link_to 'Regresar', tags_path , class:'btn btn-purple btn-icon bottom15 right15' %>
                </div> 

              </div> 
          </div>
        </div>
      </div>
  </section>
 </div>
<% end %>

app/views/tags/edit.html.erb
<%= render 'form' %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-12">
    <section class="box ">
        <header class="panel_header">
            <h2 class="title pull-left">Sensores</h2>
            <div class="actions panel_actions pull-right">
                <%= link_to 'Crear nuevo registro', new_tag_path, class: 'btn btn-primary btn-xs' %>
                <!--i class="box_toggle fa fa-chevron-down"></i>
                <i class="box_setting fa fa-cog" data-toggle="modal" href="#section-settings"></i>
                <i class="box_close fa fa-times"></i-->
            </div>
        </header>
        <div class="content-body">    
            <div class="row">
            <% @tags.each do |tag| %>
                <div class="col-lg-3 col-md-4 col-xs-12 col-sm-6">
                    <div class="tile-counter bg-primary">
                        <div class="content">
                            <i class='fa fa fa-dashboard icon-lg'></i>
                            <h2 class="number_counter1" data-speed="3000" data-from="1001" data-to="3504">ID: <%= tag.id %></h2>
                            <!--span><%= tag.name %></span-->
                            <span title="<%= tag.name %>"><%= tag.tag_type.name %></span>
                            <br>
                            <div class="btn-group btn-group-justified">
                            <%= link_to 'Editar', edit_tag_path(tag), class: 'btn btn-blue btn-xs', type:'button' %>
                            <%= link_to 'Eliminar', tag, method: :delete, data: { confirm: 'Estas Seguro de Borrar este Dispositivo?' }, class: 'btn btn-danger btn-xs', type:'button' %>      
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
                <div class="clearfix"></div>
            </div>
        </div>
    </section>
</div>

app/views/tags/new.html.erb
<%= render 'form' %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12 sort_panel">
  <section class="box purple">
    <header class="panel_header">
        <h2 class="title pull-left">Sensor</h2>
        <div class="actions panel_actions pull-right">
            <i class="box_toggle fa fa-chevron-down"></i>
            <i class="box_setting fa fa-cog" data-toggle="modal" href="#section-settings"></i>
            <i class="box_close fa fa-times"></i>
        </div>
    </header>
    <div class="content-body">    
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <p>
              <strong>Nombre:</strong>
              <%= @tag.name %>
            </p>

            <p>
              <strong>Tipo de Sensor:</strong>
              <%= @tag.tag_type.name %>
            </p>

            <p>
              <strong>Locacion:</strong>
              <%= @tag.location %>
            </p>

            <p>
              <strong>Puerto:</strong>
              <%= @tag.port %>
            </p>

            <p>
              <strong>Configuración:</strong>
              <%= @tag.config %>
            </p>

            <p>
              <strong>Dispositivo:</strong>
              <%= @tag.device.ip %>
            </p>
            <p>
              <strong>Valor Normal:</strong>
              <%= @tag.normal_value %>
            </p>
             <p>
              <strong>Valor de advertencia:</strong>
              <%= @tag.warning_value %>
            </p>
            <p>
              <strong>Valor de Peligro:</strong>
              <%= @tag.danger_value %>
            </p>
            <p>
              <strong>Humbral:</strong>
              <%= @tag.humbral %> %
            </p>

        </div>
        <div class="col-md-12">                 
           <%= link_to 'Editar', edit_tag_path(@tag) , class:'btn btn-success btn-icon bottom15 right15' %>  
           <%= link_to 'Regresar', tags_path , class:'btn btn-primary btn-icon bottom15 right15' %>
        </div> 
      </div>
    </div>
  </section>
</div>