config/routes.rb
Rails.application.routes.draw do  
  get 'signals/index'

  

  devise_for :users
  resources :tag_types
  resources :devices
  resources :tags
  

  root 'dashboard#index'

  namespace :api do  
    namespace :v1 do
        resources :tag_values, :tags, :commands, :defaults => { :format => 'json' }
    end    
  end  

  get 'telecontrol', to: 'telecontrols#index'
  post 'telecontrol', to: 'telecontrols#create'
  get 'perfil', to: 'clients#edit'
  post 'perfil', to: 'clients#update'
  get 'configuration', to: 'configuration#index'
  put 'tag_alerts/:id' => 'tag_alerts#update'
  get 'tag_alerts' => 'tag_alerts#show'
  get 'tag_notices' => 'tag_alerts#show_notices'
  put 'tag_notices/:id' => 'tag_alerts#update_notices'
  get 'signals/detail/:id', to: 'signals#detail'
  

end

app/controllers/tag_types_controller.rb
class TagTypesController < ApplicationController
  before_action :set_tag_type, only: [:show, :edit, :update, :destroy]

  # GET /tag_types
  # GET /tag_types.json
  def index
    @tag_types = TagType.all
  end

  # GET /tag_types/1
  # GET /tag_types/1.json
  def show
  end

  # GET /tag_types/new
  def new
    @tag_type = TagType.new
  end

  # GET /tag_types/1/edit
  def edit
  end

  # POST /tag_types
  # POST /tag_types.json
  def create
    @tag_type = TagType.new(tag_type_params)

    respond_to do |format|
      if @tag_type.save
        format.html { redirect_to @tag_type, notice: 'Tag type was successfully created.' }
        format.json { render :show, status: :created, location: @tag_type }
      else
        format.html { render :new }
        format.json { render json: @tag_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tag_types/1
  # PATCH/PUT /tag_types/1.json
  def update
    respond_to do |format|
      if @tag_type.update(tag_type_params)
        format.html { redirect_to @tag_type, notice: 'Tag type was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag_type }
      else
        format.html { render :edit }
        format.json { render json: @tag_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tag_types/1
  # DELETE /tag_types/1.json
  def destroy
    @tag_type.destroy
    respond_to do |format|
      format.html { redirect_to tag_types_url, notice: 'Tag type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag_type
      @tag_type = TagType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_type_params
      params.require(:tag_type).permit(:name, :tag_type, :command, :status)
    end
end

app/helpers/tag_types_helper.rb
module TagTypesHelper
end

app/views/tag_types/_form.html.erb
<%= form_for(@tag_type) do |f| %>
  <% if @tag_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag_type.errors.count, "error") %> prohibited this tag_type from being saved:</h2>

      <ul>
      <% @tag_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tag_type %><br>
    <%= f.text_field :tag_type %>
  </div>
  <div class="field">
    <%= f.label :command %><br>
    <%= f.text_field :command %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tag_types/edit.html.erb
<h1>Editing Tag Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag_type %> |
<%= link_to 'Back', tag_types_path %>

app/views/tag_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tag Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tag type</th>
      <th>Command</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tag_types.each do |tag_type| %>
      <tr>
        <td><%= tag_type.name %></td>
        <td><%= tag_type.tag_type %></td>
        <td><%= tag_type.command %></td>
        <td><%= tag_type.status %></td>
        <td><%= link_to 'Show', tag_type %></td>
        <td><%= link_to 'Edit', edit_tag_type_path(tag_type) %></td>
        <td><%= link_to 'Destroy', tag_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag type', new_tag_type_path %>

app/views/tag_types/new.html.erb
<h1>New Tag Type</h1>

<%= render 'form' %>

<%= link_to 'Back', tag_types_path %>

app/views/tag_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag_type.name %>
</p>

<p>
  <strong>Tag type:</strong>
  <%= @tag_type.tag_type %>
</p>

<p>
  <strong>Command:</strong>
  <%= @tag_type.command %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tag_type.status %>
</p>

<%= link_to 'Edit', edit_tag_type_path(@tag_type) %> |
<%= link_to 'Back', tag_types_path %>